/**
 * ╔═══════════════════════════════════════════════════════════════╗
 * ║  Full-Stack Code Generator v9.0                              ║
 * ║  Combine all captures into a runnable Node.js project        ║
 * ╚═══════════════════════════════════════════════════════════════╝
 */

import fs from 'fs/promises';
import path from 'path';

/**
 * Generate a complete runnable project from all captured data
 */
export async function generateFullStackProject(outputDir, capturedData) {
    const projectDir = path.join(outputDir, 'fullstack-clone');
    await fs.mkdir(projectDir, { recursive: true });
    await fs.mkdir(path.join(projectDir, 'public'), { recursive: true });
    await fs.mkdir(path.join(projectDir, 'api'), { recursive: true });
    await fs.mkdir(path.join(projectDir, 'fixtures'), { recursive: true });

    const { apiData, wsData, authData, interactionData, dynamicData, webglData } = capturedData;

    // ═══ 1. Copy clone files to public/ ═══
    const cloneDir = path.join(outputDir, 'clone');
    try {
        const files = await fs.readdir(cloneDir);
        for (const file of files) {
            await fs.copyFile(path.join(cloneDir, file), path.join(projectDir, 'public', file));
        }
    } catch { }

    // Copy assets
    const assetsDir = path.join(outputDir, 'assets');
    try {
        await copyRecursive(assetsDir, path.join(projectDir, 'public', 'assets'));
    } catch { }

    // ═══ 2. Copy fixtures ═══
    const mockServerDir = path.join(outputDir, 'mock-server');
    try {
        await copyRecursive(path.join(mockServerDir, 'fixtures'), path.join(projectDir, 'fixtures'));
    } catch { }
    try {
        await copyRecursive(path.join(mockServerDir, 'ws-fixtures'), path.join(projectDir, 'fixtures', 'ws'));
    } catch { }
    try {
        await copyRecursive(path.join(mockServerDir, 'dynamic-fixtures'), path.join(projectDir, 'fixtures', 'dynamic'));
    } catch { }

    // ═══ 3. Generate server.mjs ═══
    const hasAPI = apiData?.apiEndpoints?.length > 0;
    const hasWS = wsData?.stats?.messages > 0;
    const hasAuth = authData?.authType && authData.authType !== 'none';

    let serverCode = `#!/usr/bin/env node
/**
 * ═══ Design-DNA Full-Stack Clone Server ═══
 * Generated by Design-DNA v9.0
 * 
 * Features:
 *  • Static site serving (clone)
 *  • API mock server (${hasAPI ? apiData.apiEndpoints.length + ' endpoints' : 'none'})
 *  • WebSocket replay (${hasWS ? 'enabled' : 'none'})
 *  • Auth mock (${hasAuth ? authData.authType : 'none'})
 */

import express from 'express';
import cors from 'cors';
import path from 'path';
import fs from 'fs';
import http from 'http';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
const server = http.createServer(app);
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Request logger
app.use((req, res, next) => {
    if (!req.path.match(/\\.(css|js|png|jpg|svg|woff|ico)$/)) {
        console.log(\`  \${req.method} \${req.path}\`);
    }
    next();
});

// ═══ Fixture loader ═══
function loadFixture(name) {
    try { return JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures', name), 'utf-8')); }
    catch { return null; }
}

`;

    // API routes
    if (hasAPI) {
        serverCode += `// ═══ API Mock Routes ═══\n`;
        for (const ep of apiData.apiEndpoints) {
            const method = ep.method.toLowerCase();
            const routePath = ep.path.replace(/\/(\d+)(?=\/|$)/g, '/:id');
            const fixFile = sanitize(ep.key) + '.json';
            serverCode += `app.${method}('${routePath}', (req, res) => {\n`;
            serverCode += `    const f = loadFixture('${fixFile}');\n`;
            serverCode += `    f ? res.status(f.status||200).json(f.response) : res.json({});\n`;
            serverCode += `});\n`;
        }
        serverCode += `\n// GraphQL\n`;
        serverCode += `app.post('/graphql', (req, res) => {\n`;
        serverCode += `    const ops = loadFixture('_graphql-operations.json') || [];\n`;
        serverCode += `    const match = ops.find(o => o.operationName === req.body?.operationName);\n`;
        serverCode += `    res.json(match ? { data: match.response || {} } : { data: {} });\n`;
        serverCode += `});\n\n`;
    }

    // Auth routes
    if (hasAuth) {
        serverCode += `// ═══ Auth Mock Routes ═══\n`;
        serverCode += `function mockJWT() {\n`;
        serverCode += `    const h = Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url');\n`;
        serverCode += `    const p = Buffer.from(JSON.stringify({sub:'1',name:'Test User',email:'test@example.com',exp:Math.floor(Date.now()/1000)+86400})).toString('base64url');\n`;
        serverCode += `    return h+'.'+p+'.mock-sig';\n`;
        serverCode += `}\n\n`;
        serverCode += `app.post('/api/auth/login', (req, res) => {\n`;
        serverCode += `    res.json({ success: true, token: mockJWT(), user: { id: 1, email: req.body?.email || 'test@example.com', name: 'Test User' } });\n`;
        serverCode += `});\n`;
        serverCode += `app.post('/api/auth/signup', (req, res) => {\n`;
        serverCode += `    res.json({ success: true, token: mockJWT(), user: { id: 2, ...req.body } });\n`;
        serverCode += `});\n`;
        serverCode += `app.get('/api/auth/me', (req, res) => {\n`;
        serverCode += `    req.headers.authorization ? res.json({ id: 1, email: 'test@example.com', name: 'Test User' }) : res.status(401).json({ error: 'Unauthorized' });\n`;
        serverCode += `});\n`;
        serverCode += `app.post('/api/auth/logout', (req, res) => res.json({ success: true }));\n\n`;
    }

    // Catch-all API
    serverCode += `// API catch-all\napp.all('/api/*', (req, res) => res.json({ data: [], mock: true }));\n\n`;

    // WebSocket replay
    if (hasWS) {
        serverCode += `// ═══ WebSocket Replay ═══\n`;
        serverCode += `import { WebSocketServer } from 'ws';\n`;
        serverCode += `const wss = new WebSocketServer({ server, path: '/ws' });\n`;
        serverCode += `const wsMessages = loadFixture('ws/messages.json') || [];\n`;
        serverCode += `const incoming = wsMessages.filter(m => m.dir === 'in');\n`;
        serverCode += `wss.on('connection', ws => {\n`;
        serverCode += `    let i = 0;\n`;
        serverCode += `    function next() {\n`;
        serverCode += `        if (i >= incoming.length) { i = 0; setTimeout(next, 3000); return; }\n`;
        serverCode += `        try { ws.send(incoming[i].data); } catch {}\n`;
        serverCode += `        const d = incoming[i+1] ? Math.min(incoming[i+1].ts - incoming[i].ts, 5000) : 3000;\n`;
        serverCode += `        i++; setTimeout(next, Math.max(d, 100));\n`;
        serverCode += `    }\n`;
        serverCode += `    setTimeout(next, 500);\n`;
        serverCode += `});\n\n`;
    }

    // Static files (clone)
    serverCode += `// ═══ Static Files (Clone) ═══\n`;
    serverCode += `app.use(express.static(path.join(__dirname, 'public')));\n`;
    serverCode += `app.get('*', (req, res) => res.sendFile(path.join(__dirname, 'public', 'index.html')));\n\n`;

    // Start server
    serverCode += `// ═══ Start ═══\n`;
    serverCode += `server.listen(PORT, () => {\n`;
    serverCode += `    console.log('');\n`;
    serverCode += `    console.log('  ╔════════════════════════════════════════╗');\n`;
    serverCode += `    console.log('  ║  Design-DNA Full-Stack Clone Server   ║');\n`;
    serverCode += `    console.log('  ╚════════════════════════════════════════╝');\n`;
    serverCode += `    console.log('');\n`;
    serverCode += `    console.log('  🌐 Site:    http://localhost:' + PORT);\n`;
    if (hasAPI) serverCode += `    console.log('  📡 API:     http://localhost:' + PORT + '/api');\n`;
    if (hasWS) serverCode += `    console.log('  🔌 WS:      ws://localhost:' + PORT + '/ws');\n`;
    if (hasAuth) serverCode += `    console.log('  🔐 Auth:    http://localhost:' + PORT + '/api/auth/login');\n`;
    serverCode += `    console.log('');\n`;
    serverCode += `});\n`;

    await fs.writeFile(path.join(projectDir, 'server.mjs'), serverCode, 'utf-8');

    // ═══ 4. Generate package.json ═══
    const deps = { express: '^4.18.0', cors: '^2.8.5' };
    if (hasWS) deps.ws = '^8.16.0';

    const pkg = {
        name: 'design-dna-fullstack-clone',
        version: '1.0.0',
        type: 'module',
        scripts: {
            start: 'node server.mjs',
            dev: 'node --watch server.mjs',
        },
        dependencies: deps,
    };
    await fs.writeFile(path.join(projectDir, 'package.json'), JSON.stringify(pkg, null, 2), 'utf-8');

    // ═══ 5. Generate README ═══
    const readme = `# Full-Stack Clone (Design-DNA v9.0)\n\n## Quick Start\n\`\`\`bash\nnpm install\nnpm start\n\`\`\`\n\nOpen http://localhost:3000\n\n## Features\n- Static site clone\n${hasAPI ? '- API mock server (' + apiData.apiEndpoints.length + ' endpoints)\n' : ''}${hasWS ? '- WebSocket replay\n' : ''}${hasAuth ? '- Auth mock (' + authData.authType + ')\n' : ''}\n`;
    await fs.writeFile(path.join(projectDir, 'README.md'), readme, 'utf-8');

    // ═══ 6. Generate Dockerfile ═══
    const dockerfile = `FROM node:20-alpine\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci --production\nCOPY . .\nEXPOSE 3000\nCMD ["npm", "start"]\n`;
    await fs.writeFile(path.join(projectDir, 'Dockerfile'), dockerfile, 'utf-8');

    return {
        projectDir,
        files: ['server.mjs', 'package.json', 'README.md', 'Dockerfile'],
        features: { api: hasAPI, ws: hasWS, auth: hasAuth },
    };
}

async function copyRecursive(src, dest) {
    await fs.mkdir(dest, { recursive: true });
    const entries = await fs.readdir(src, { withFileTypes: true });
    for (const entry of entries) {
        const srcPath = path.join(src, entry.name);
        const destPath = path.join(dest, entry.name);
        if (entry.isDirectory()) {
            await copyRecursive(srcPath, destPath);
        } else {
            await fs.copyFile(srcPath, destPath);
        }
    }
}

function sanitize(str) {
    return str.replace(/[^a-zA-Z0-9-]/g, '_').replace(/_+/g, '_').substring(0, 80);
}
