/**
 * Upgrade 8: React Component Generation
 * Generates React/JSX component code from extracted layout and design tokens
 */

export function generateReactComponents(layoutData, tokensData, interactionData) {
    const files = {};

    // ── 1. Design System file ──
    files['design-system.css'] = generateDesignSystemCSS(tokensData);

    // ── 2. Section components ──
    if (layoutData?.sections?.length) {
        files['PageLayout.jsx'] = generatePageLayout(layoutData);

        layoutData.sections.forEach((section, i) => {
            const name = componentName(section.name || `Section${i}`);
            files[`${name}.jsx`] = generateSectionComponent(section, name, i);
        });
    }

    // ── 3. Shared components ──
    files['AnimatedReveal.jsx'] = generateRevealComponent();
    files['MagneticCursor.jsx'] = generateCursorComponent(interactionData);

    return files;
}

function generateDesignSystemCSS(tokens) {
    const lines = [
        '/* ═══════════════════════════════════════════════ */',
        '/* Design System — Auto-generated by design-dna   */',
        '/* ═══════════════════════════════════════════════ */',
        '',
    ];

    // CSS reset fragment
    lines.push('*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }');
    lines.push('');

    // Variables
    lines.push(':root {');
    if (tokens?.typography?.fonts?.length) {
        lines.push(`  --font-primary: "${tokens.typography.fonts[0]}", sans-serif;`);
        if (tokens.typography.fonts[1]) {
            lines.push(`  --font-secondary: "${tokens.typography.fonts[1]}", sans-serif;`);
        }
    }

    if (tokens?.colors?.backgrounds) {
        let i = 0;
        Object.keys(tokens.colors.backgrounds).slice(0, 10).forEach(color => {
            lines.push(`  --color-bg-${i++}: ${color};`);
        });
    }

    if (tokens?.colors?.texts) {
        let i = 0;
        Object.keys(tokens.colors.texts).slice(0, 5).forEach(color => {
            lines.push(`  --color-text-${i++}: ${color};`);
        });
    }
    lines.push('}');

    return lines.join('\n');
}

function generatePageLayout(layout) {
    const sections = layout.sections || [];
    const imports = sections.map((s, i) => {
        const name = componentName(s.name || `Section${i}`);
        return `import ${name} from "./${name}";`;
    }).join('\n');

    return `// Auto-generated Page Layout — design-dna v4.0
import React from "react";
import AnimatedReveal from "./AnimatedReveal";
${imports}

export default function PageLayout() {
  return (
    <main>
      ${sections.map((s, i) => {
        const name = componentName(s.name || `Section${i}`);
        return `<AnimatedReveal>
        <${name} />
      </AnimatedReveal>`;
    }).join('\n      ')}
    </main>
  );
}
`;
}

function generateSectionComponent(section, name, index) {
    const bgStyle = section.backgroundColor && section.backgroundColor !== 'rgba(0, 0, 0, 0)'
        ? `backgroundColor: "${section.backgroundColor}"`
        : '';
    const paddingStyle = section.padding !== '0px' ? `padding: "${section.padding}"` : '';
    const styleProps = [bgStyle, paddingStyle].filter(Boolean).join(', ');

    return `// Auto-generated — design-dna v4.0
// Original: ${section.tag} "${section.name}" — ${section.bounds?.width}×${section.bounds?.height}px
import React from "react";

export default function ${name}() {
  return (
    <section
      className="dna-section dna-section-${index}"
      style={{
        ${styleProps}
        minHeight: "${section.bounds?.height}px",
        width: "100%",
        position: "relative",
      }}
    >
      <div className="dna-container">
        {/* ${section.children || 0} child elements in original */}
        <h2>${section.name?.substring(0, 50) || `Section ${index + 1}`}</h2>
      </div>
    </section>
  );
}
`;
}

function generateRevealComponent() {
    return `// Scroll-triggered reveal animation — design-dna v4.0
import React, { useRef, useEffect, useState } from "react";

export default function AnimatedReveal({ children, delay = 0 }) {
  const ref = useRef(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisible(true);
          observer.disconnect();
        }
      },
      { threshold: 0.1, rootMargin: "0px 0px -50px 0px" }
    );

    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, []);

  return (
    <div
      ref={ref}
      style={{
        opacity: visible ? 1 : 0,
        transform: visible ? "translateY(0)" : "translateY(40px)",
        transition: \`opacity 0.8s ease \${delay}s, transform 0.8s cubic-bezier(0.16, 1, 0.3, 1) \${delay}s\`,
      }}
    >
      {children}
    </div>
  );
}
`;
}

function generateCursorComponent(interaction) {
    const hasCursor = interaction?.customCursors?.length > 0;
    const cursor = hasCursor ? interaction.customCursors[0] : null;
    const size = cursor?.size?.width || 20;

    return `// Custom magnetic cursor — design-dna v4.0
import React, { useEffect, useRef } from "react";

export default function MagneticCursor({ size = ${size}, blendMode = "${cursor?.mixBlendMode || 'difference'}" }) {
  const cursorRef = useRef(null);

  useEffect(() => {
    const cursor = cursorRef.current;
    if (!cursor) return;

    const move = (e) => {
      cursor.style.left = e.clientX + "px";
      cursor.style.top = e.clientY + "px";
    };

    window.addEventListener("mousemove", move);
    return () => window.removeEventListener("mousemove", move);
  }, []);

  return (
    <div
      ref={cursorRef}
      style={{
        position: "fixed",
        width: size + "px",
        height: size + "px",
        borderRadius: "50%",
        background: "white",
        mixBlendMode: blendMode,
        pointerEvents: "none",
        transform: "translate(-50%, -50%)",
        transition: "width 0.3s, height 0.3s",
        zIndex: 9999,
      }}
    />
  );
}
`;
}

function componentName(name) {
    // Convert to PascalCase
    return name
        .replace(/[^a-zA-Z0-9 ]/g, '')
        .split(/[\s_-]+/)
        .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
        .join('')
        .substring(0, 30) || 'Section';
}
