import fs from 'fs';
const d = JSON.parse(fs.readFileSync('./live-test-evople/dna-report.json', 'utf8'));
const r = [];

r.push('=== LIVE TEST RESULTS: teamevople.kr ===');
r.push('');
r.push('COLORS: bg=' + Object.keys(d.tokens?.colors?.backgrounds || {}).length + ' text=' + Object.keys(d.tokens?.colors?.textColors || {}).length);
r.push('FONTS: ' + JSON.stringify(d.tokens?.typography?.fonts));
r.push('SECTIONS: ' + d.layout?.sections?.length);
r.push('GRIDS: ' + d.layout?.grids?.length + ' FLEX: ' + d.layout?.flexboxes?.length);
r.push('KEYFRAMES: ' + d.animation?.keyframes?.length + ' TRANSITIONS: ' + d.animation?.transitions?.length);
r.push('BREAKPOINTS: ' + JSON.stringify(d.responsive?.breakpoints?.map(b => b.width)));
r.push('HOVERS: ' + d.interaction?.hovers?.length);
r.push('LIBS: ' + JSON.stringify(d.techStack?.libraries?.map(l => l.name)));
r.push('PERF: FCP=' + d.performance?.fcp + ' LCP=' + d.performance?.lcp + ' CLS=' + d.performance?.cls);
r.push('A11Y: score=' + d.accessibility?.score + ' issues=' + d.accessibility?.issues?.length);
r.push('LH: ' + JSON.stringify(d.lighthouse?.scores));
r.push('CRAWL: ' + d.crawl?.total + ' pages');
r.push('RUNTIME: IO=' + d.runtimeHook?.intersectionObservers?.length + ' raf=' + d.runtimeHook?.rafCallbackCount);
r.push('SVG: total=' + d.svgAnimations?.totalSVGCount + ' cssAnim=' + d.svgAnimations?.cssAnimatedSVGs?.length);
r.push('CSS+: viewTrans=' + d.cssAdvanced?.summary?.viewTransitions + ' supports=' + d.cssAdvanced?.summary?.supportsConditions);
r.push('API: endpoints=' + d.apiIntelligence?.apiEndpoints?.length + ' cookies=' + d.apiIntelligence?.cookies?.length);
r.push('AUTH: forms=' + d.authFlow?.loginForms?.length);
r.push('SPA: routes=' + d.spaRoutes?.discoveredRoutes?.length + ' analyzed=' + d.spaRoutes?.analyzedRoutes?.length);
r.push('CANVAS: ' + d.canvasCapture?.totalCanvases);
r.push('INTERACT: modals=' + d.interactions?.modals?.length + ' tabs=' + d.interactions?.tabs?.length);
r.push('');
r.push('=== IDENTIFIED GAPS ===');
r.push('1. NO AI SCORING - raw data only, no quality assessment');
r.push('2. NO COLOR HARMONY - hex/rgb values but no psychology/mood analysis');
r.push('3. NO LAYOUT PATTERN CLASSIFICATION - grid/flex counts but no "hero section" or "card grid" naming');
r.push('4. NO FONT PAIRING ANALYSIS - font names but no pairing quality scoring');
r.push('5. NO UX PREDICTION - no usability/conversion scoring from design signals');
r.push('6. NO VISUAL HIERARCHY MAP - no weighting, no flow analysis');
r.push('7. NO TREND DETECTION - no era/style classification (brutalist, glassmorphism, etc)');
r.push('8. NO COMPONENT DETECTION - no naming of UI patterns (CTA, testimonial, pricing card)');
r.push('');
r.push('TOTAL KEYS: ' + Object.keys(d).length);
r.push('FILE SIZE: ' + Math.round(fs.statSync('./live-test-evople/dna-report.json').size / 1024) + 'KB');

fs.writeFileSync('./deep-analysis.txt', r.join('\n'), 'utf8');
console.log('Done - see deep-analysis.txt');
